version: "3"
services:
  web:
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./setup/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
  php:
    build:
      context: ./setup
      dockerfile: PHP.Dockerfile
    volumes:
      - ./src:/var/www
  mysql:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=secure_password
      - MYSQL_DATABASE=demo
      - MYSQL_RANDOM_ROOT_PASSWORD=true